# Generated by Django 5.2.1 on 2025-05-09 13:19

import django.db.models.deletion
import extractor.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=extractor.models.pdf_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('ANALYZED', 'Analyzed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SENDIGDomain',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_variables', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('xpt_file', models.FileField(blank=True, null=True, upload_to='xpt_files')),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='extractor.pdfdocument')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.sendigdomain')),
            ],
            options={
                'unique_together': {('pdf', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='DetectedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(help_text='Comma-separated list of page numbers or ranges', max_length=255)),
                ('selected', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_domains', to='extractor.pdfdocument')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractor.sendigdomain')),
            ],
            options={
                'unique_together': {('pdf', 'domain')},
            },
        ),
    ]
